# Generated by Django 4.2.10 on 2024-10-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_replymessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replymessage',
            old_name='replyAuthor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='replymessage',
            name='content',
            field=models.TextField(verbose_name='Контент ответа на коммент'),
        ),
    ]
